//@ts-ignore
import { ChakraProvider } from "@chakra-ui/react";
//@ts-ignore
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
          <ChakraProvider cssVarsRoot="body">
            {children}
          </ChakraProvider>
      </body>
    </html>
  )
}
